
export default {
  ADD_B_CONTRACT: 'ADD_BUSINESS_CONTRACT',
  B_FETCH: 'FETCH_BUSINESS_CONTRACTS',
  B_UPDATE: 'UPDATE_BUSINESS_SEARCH',
  B_DELETE: 'DELETE_BUSINESS_CONTRACT_BY_ID',
  ADD_W_CONTRACT: 'ADD_WORK_CONTRACT',
  W_FETCH: 'FETCH_WORK_CONTRACTS',
  W_UPDATE: 'UPDATE_WORK_SEARCH',
  W_DELETE: 'DELETE_WORK_CONTRACT_BY_ID',
}