import { makeStyles } from '@material-ui/core';
import React from 'react';

const Spacing: React.FC<any> = ({
  p0, pt0, pr0, pb0, pl0, ph0, pv0, m0, mt0, mr0, mb0, ml0, mv0, mh0,
  p1, pt1, pr1, pb1, pl1, ph1, pv1, m1, mt1, mr1, mb1, ml1, mv1, mh1,
  p2, pt2, pr2, pb2, pl2, ph2, pv2, m2, mt2, mr2, mb2, ml2, mv2, mh2,
  p3, pt3, pr3, pb3, pl3, ph3, pv3, m3, mt3, mr3, mb3, ml3, mv3, mh3,
  p4, pt4, pr4, pb4, pl4, ph4, pv4, m4, mt4, mr4, mb4, ml4, mv4, mh4,
  p5, pt5, pr5, pb5, pl5, ph5, pv5, m5, mt5, mr5, mb5, ml5, mv5, mh5,
  className,
  children,
  ...props
}) => {
  const classes = useStyles()
  const spacingStyle = [
    p0 ? classes.p0: '', pt0 ? classes.pt0: '', 
    pr0 ? classes.pr0: '', pb0 ? classes.pt0: '',
    pl0 ? classes.pl0: '', m0 ? classes.m0: '',
    mt0 ? classes.mt0: '', mr0 ? classes.mr0: '',
    mb0 ? classes.mb0: '', ml0 ? classes.ml0: '',
    p1 ? classes.p1: '', pt1 ? classes.pt1: '', 
    pr1 ? classes.pr1: '', pb1 ? classes.pb1: '',
    pl1 ? classes.pl1: '', m1 ? classes.m1: '',
    mt1 ? classes.mt1: '', mr1 ? classes.mr1: '',
    mb1 ? classes.mb1: '', ml1 ? classes.ml1: '',
    p2 ? classes.p2: '', pt2 ? classes.pt2: '', 
    pr2 ? classes.pr2: '', pb2 ? classes.pt2: '',
    pl2 ? classes.pl2: '', m2 ? classes.m2: '',
    mt2 ? classes.mt2: '', mr2 ? classes.mr2: '',
    mb2 ? classes.mb2: '', ml2 ? classes.ml2: '',
    p3 ? classes.p3: '', pt3 ? classes.pt3: '', 
    pr3 ? classes.pr3: '', pb3 ? classes.pb3: '',
    pl3 ? classes.pl3: '', m3 ? classes.m3: '',
    mt3 ? classes.mt3: '', mr3 ? classes.mr3: '',
    mb3 ? classes.mb3: '', ml3 ? classes.ml3: '',
    p4 ? classes.p4: '', pt4 ? classes.pt4: '', 
    pr4 ? classes.pr4: '', pb4 ? classes.pb4: '',
    pl4 ? classes.pl4: '', m4 ? classes.m4: '',
    mt4 ? classes.mt4: '', mr4 ? classes.mr4: '',
    mb4 ? classes.mb4: '', ml4 ? classes.ml4: '',
    p5 ? classes.p5: '', pt5 ? classes.pt5: '', 
    pr5 ? classes.pr5: '', pb5 ? classes.p5: '',
    pl5 ? classes.pl5: '', m5 ? classes.m5: '',
    mt5 ? classes.mt5: '', mr5 ? classes.mr5: '',
    mb5 ? classes.mb5: '', ml5 ? classes.ml5: '',
    mv0 ? classes.mv0: '', mh0 ? classes.mh0: '',
    mv1 ? classes.mv1: '', mh1 ? classes.mh1: '',
    mv2 ? classes.mv2: '', mh2 ? classes.mh2: '',
    mv3 ? classes.mv3: '', mh3 ? classes.mh3: '',
    mv4 ? classes.mv4: '', mh4 ? classes.mh4: '',
    mv5 ? classes.mv5: '', mh5 ? classes.mh5: '',
    pv0 ? classes.pv0: '', ph0 ? classes.ph0: '',
    pv1 ? classes.pv1: '', ph1 ? classes.ph1: '',
    pv2 ? classes.pv2: '', ph2 ? classes.ph2: '',
    pv3 ? classes.pv3: '', ph3 ? classes.ph3: '',
    pv4 ? classes.pv4: '', ph4 ? classes.ph4: '',
    pv5 ? classes.pv5: '', ph5 ? classes.ph5: '',
    className ? className: '',
  ].filter(Boolean);

  return ( 
    <div className={spacingStyle.join(" ")} {...props}>
      {children}
    </div>
   );
}

const useStyles = makeStyles((theme) => ({
  p0: { padding: theme.spacing(0) },
  p1: { padding: theme.spacing(1) },
  p2: { padding: theme.spacing(2) },
  p3: { padding: theme.spacing(3) },
  p4: { padding: theme.spacing(4) },
  p5: { padding: theme.spacing(5) },
  m0: { margin: theme.spacing(0) },
  m1: { margin: theme.spacing(1) },
  m2: { margin: theme.spacing(2) },
  m3: { margin: theme.spacing(3) },
  m4: { margin: theme.spacing(4) },
  m5: { margin: theme.spacing(5) },
  pv0: { padding: theme.spacing(0, 0) },
  pv1: { padding: theme.spacing(1, 0) },
  pv2: { padding: theme.spacing(2, 0) },
  pv3: { padding: theme.spacing(3, 0) },
  pv4: { padding: theme.spacing(4, 0) },
  pv5: { padding: theme.spacing(5, 0) },
  mv0: { margin: theme.spacing(0, 0) },
  mv1: { margin: theme.spacing(1, 0) },
  mv2: { margin: theme.spacing(2, 0) },
  mv3: { margin: theme.spacing(3, 0) },
  mv4: { margin: theme.spacing(4, 0) },
  mv5: { margin: theme.spacing(5, 0) },
  ph0: { padding: theme.spacing(0, 0) },
  ph1: { padding: theme.spacing(0, 1) },
  ph2: { padding: theme.spacing(0, 2) },
  ph3: { padding: theme.spacing(0, 3) },
  ph4: { padding: theme.spacing(0, 4) },
  ph5: { padding: theme.spacing(0, 5) },
  mh0: { margin: theme.spacing(0, 0) },
  mh1: { margin: theme.spacing(0, 1) },
  mh2: { margin: theme.spacing(0, 2) },
  mh3: { margin: theme.spacing(0, 3) },
  mh4: { margin: theme.spacing(0, 4) },
  mh5: { margin: theme.spacing(0, 5) },
  pt0: { padding: theme.spacing(0, 0, 0, 0) },
  pt1: { padding: theme.spacing(1, 0, 0, 0) },
  pt2: { padding: theme.spacing(2, 0, 0, 0) },
  pt3: { padding: theme.spacing(3, 0, 0, 0) },
  pt4: { padding: theme.spacing(4, 0, 0, 0) },
  pt5: { padding: theme.spacing(5, 0, 0, 0) },
  mt0: { margin: theme.spacing(0, 0, 0, 0) },
  mt1: { margin: theme.spacing(1, 0, 0, 0) },
  mt2: { margin: theme.spacing(2, 0, 0, 0) },
  mt3: { margin: theme.spacing(3, 0, 0, 0) },
  mt4: { margin: theme.spacing(4, 0, 0, 0) },
  mt5: { margin: theme.spacing(5, 0, 0, 0) },
  pr0: { padding: theme.spacing(0, 0, 0, 0) },
  pr1: { padding: theme.spacing(0, 1, 0, 0) },
  pr2: { padding: theme.spacing(0, 2, 0, 0) },
  pr3: { padding: theme.spacing(0, 3, 0, 0) },
  pr4: { padding: theme.spacing(0, 4, 0, 0) },
  pr5: { padding: theme.spacing(0, 5, 0, 0) },
  mr0: { margin: theme.spacing(0, 0, 0, 0) },
  mr1: { margin: theme.spacing(0, 1, 0, 0) },
  mr2: { margin: theme.spacing(0, 2, 0, 0) },
  mr3: { margin: theme.spacing(0, 3, 0, 0) },
  mr4: { margin: theme.spacing(0, 4, 0, 0) },
  mr5: { margin: theme.spacing(0, 5, 0, 0) },
  pb0: { padding: theme.spacing(0, 0, 0, 0) },
  pb1: { padding: theme.spacing(0, 0, 1, 0) },
  pb2: { padding: theme.spacing(0, 0, 2, 0) },
  pb3: { padding: theme.spacing(0, 0, 3, 0) },
  pb4: { padding: theme.spacing(0, 0, 4, 0) },
  pb5: { padding: theme.spacing(0, 0, 5, 0) },
  mb0: { margin: theme.spacing(0, 0, 0, 0) },
  mb1: { margin: theme.spacing(0, 0, 1, 0) },
  mb2: { margin: theme.spacing(0, 0, 2, 0) },
  mb3: { margin: theme.spacing(0, 0, 3, 0) },
  mb4: { margin: theme.spacing(0, 0, 4, 0) },
  mb5: { margin: theme.spacing(0, 0, 5, 0) },
  pl0: { padding: theme.spacing(0, 0, 0, 0) },
  pl1: { padding: theme.spacing(0, 0, 0, 1) },
  pl2: { padding: theme.spacing(0, 0, 0, 2) },
  pl3: { padding: theme.spacing(0, 0, 0, 3) },
  pl4: { padding: theme.spacing(0, 0, 0, 4) },
  pl5: { padding: theme.spacing(0, 0, 0, 5) },
  ml0: { margin: theme.spacing(0, 0, 0, 0) },
  ml1: { margin: theme.spacing(0, 0, 0, 1) },
  ml2: { margin: theme.spacing(0, 0, 0, 2) },
  ml3: { margin: theme.spacing(0, 0, 0, 3) },
  ml4: { margin: theme.spacing(0, 0, 0, 4) },
  ml5: { margin: theme.spacing(0, 0, 0, 5) },
}))
 
export default Spacing;