name: Continuous Integration
on:
  pull_request:
    branches: [ "development" ]
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: jest
      - run: npm run build
